version: '3.8'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  celery_worker:
    environment:
      - DEBUG=True
    volumes:
      - .:/app

  celery_beat:
    environment:
      - DEBUG=True
    volumes:
      - .:/app

  telegram_bot:
    environment:
      - DEBUG=True
    volumes:
      - .:/app

  nginx:
    ports: []