# Generated by Django 5.2.7 on 2025-10-22 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(help_text='Введите место, где необходимо выполнить привычку', max_length=200, verbose_name='Место')),
                ('lead_time', models.DateTimeField()),
                ('action', models.TextField(verbose_name='Действие')),
                ('pleasant_habit', models.BooleanField(default=False, help_text='Выберете приятная ли это привычка', verbose_name='Признак приятной привычки')),
                ('period', models.PositiveSmallIntegerField(help_text='Введите периодичность выполнения привычки в днях, но не более 7', validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 день'), django.core.validators.MaxValueValidator(7, message='Максимум 7 дней')], verbose_name='Периодичность (в днях)')),
                ('time_to_complete', models.PositiveIntegerField(help_text='Введите время за которое вы выполните привычку, но не более 120 секунд', validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 секунда'), django.core.validators.MaxValueValidator(120, message='Максимум 120 секунд')], verbose_name='Время на выполнение привычки')),
                ('public', models.BooleanField(default=False, help_text='Публикация в общий доступ', verbose_name='Признак публичности привычки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Habit', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Указывается только для полезных привычек', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ['lead_time'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Описание вознаграждения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Award', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_habit', to='habits.habit', verbose_name='Habit')),
            ],
            options={
                'verbose_name': 'вознаграждение',
                'verbose_name_plural': 'вознаграждения',
            },
        ),
    ]
